/** Seed data: taxonomy + human-truth insights. */

export const TAXONOMY: Record<string, string[]> = {
  SELF: ["identity", "self-worth", "shame", "guilt", "insecurity", "authenticity", "self-deception"],
  EGO: ["pride", "status", "validation", "envy", "comparison", "superiority", "resentment", "need-to-be-right"],
  DESIRE: ["pleasure", "greed", "craving", "novelty", "consumption", "ambition", "instant-gratification"],
  FEAR: ["rejection", "failure", "abandonment", "death", "uncertainty", "judgment", "change", "loneliness"],
  ATTACHMENT: ["people", "memories", "possessions", "beliefs", "identity", "status", "past", "expectations"],
  RELATIONSHIPS: ["love", "dependency", "betrayal", "family", "friendship", "marriage", "forgiveness", "boundaries"],
  CHARACTER: ["discipline", "courage", "honesty", "patience", "responsibility", "temptation", "integrity", "self-control"],
  SUFFERING: ["loss", "regret", "disappointment", "grief", "frustration", "meaninglessness", "unfairness"],
  MEANING: ["mortality", "time", "purpose", "legacy", "faith", "gratitude", "service", "transcendence"],
  SOCIETY: ["money", "success", "work", "social-media", "consumerism", "fame", "power", "conformity", "status-signaling"],
};

export type InsightSeed = {
  statement: string;
  observation: string;
  desire: string;
  hiddenFear: string;
  contradictoryBehavior: string;
  cost: string;
  category: string;
  node: string;
  secondaryConflicts?: string[];
  universalityScore: number;
  depthScore: number;
  noveltyScore: number;
  recognitionScore: number;
  status: "approved" | "candidate" | "needs_research" | "used" | "rejected" | "retired";
  emotions?: string[];
  domains?: string[];
  lenses?: string[];
  exceptional?: boolean;
};

export const INSIGHT_SEEDS: InsightSeed[] = [
  {
    statement: "We defend our self-image more fiercely than we pursue the truth about ourselves.",
    observation: "People will rewrite history, blame circumstance, or attack the messenger before admitting they were wrong about who they are.",
    desire: "To remain coherent and worthy in one's own eyes.",
    hiddenFear: "That the self is a construction that would collapse under honest inspection.",
    contradictoryBehavior: "Asking for feedback while punishing honesty; journaling for growth while editing out shame.",
    cost: "Stagnation disguised as confidence; relationships that never get past the performance.",
    category: "SELF",
    node: "self-deception",
    secondaryConflicts: ["EGO/pride", "FEAR/judgment"],
    universalityScore: 0.92,
    depthScore: 0.88,
    noveltyScore: 0.55,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["shame", "pride"],
    domains: ["identity", "growth"],
    lenses: ["psychological", "stoic"], exceptional: true,
  },
  {
    statement: "Shame is not the belief that you did something bad — it is the belief that you are something bad.",
    observation: "Guilt points at an action; shame paints the whole person. People hide, overcompensate, or self-sabotage when shame is active.",
    desire: "To be fundamentally acceptable.",
    hiddenFear: "Irredeemable defectiveness.",
    contradictoryBehavior: "Perfectionism paired with secret self-destruction.",
    cost: "Isolation; inability to receive love without suspicion.",
    category: "SELF",
    node: "shame",
    secondaryConflicts: ["RELATIONSHIPS/love", "FEAR/rejection"],
    universalityScore: 0.94,
    depthScore: 0.91,
    noveltyScore: 0.4,
    recognitionScore: 0.93,
    status: "approved",
    emotions: ["shame", "fear"],
    domains: ["identity", "healing"],
    lenses: ["psychological"], exceptional: true,
  },
  {
    statement: "Insecurity often wears the costume of high standards.",
    observation: "What looks like excellence-seeking is frequently a refusal to be seen as average — the standard rises so the self never has to land.",
    desire: "To feel safe from judgment by staying above the fray.",
    hiddenFear: "Being ordinary and therefore discardable.",
    contradictoryBehavior: "Criticizing others' low standards while never finishing one's own work.",
    cost: "Chronic dissatisfaction; envy of people who enjoy imperfect lives.",
    category: "SELF",
    node: "insecurity",
    secondaryConflicts: ["EGO/comparison", "FEAR/judgment"],
    universalityScore: 0.89,
    depthScore: 0.82,
    noveltyScore: 0.62,
    recognitionScore: 0.87,
    status: "approved",
    emotions: ["anxiety", "envy"],
    domains: ["work", "identity"],
    lenses: ["psychological", "cultural"],
  },
  {
    statement: "Authenticity is often delayed until the cost of performing becomes higher than the cost of being seen.",
    observation: "People find themselves after burnout, betrayal, or exile — not because truth suddenly arrived, but because the mask became unaffordable.",
    desire: "Belonging without the labor of constant editing.",
    hiddenFear: "That the real self will not be loved.",
    contradictoryBehavior: "Preaching authenticity while curating every vulnerability for effect.",
    cost: "Years lived as a character; grief for a life that wasn't fully inhabited.",
    category: "SELF",
    node: "authenticity",
    secondaryConflicts: ["EGO/validation", "FEAR/rejection"],
    universalityScore: 0.9,
    depthScore: 0.86,
    noveltyScore: 0.58,
    recognitionScore: 0.88,
    status: "approved",
    emotions: ["longing", "relief"],
    domains: ["identity", "relationships"],
    lenses: ["existential", "psychological"],
  },
  {
    statement: "Self-worth that depends on winning must treat every peer as a threat.",
    observation: "Conditional self-worth turns collaboration into covert competition and rest into guilt.",
    desire: "Stable worth that doesn't reset every Monday.",
    hiddenFear: "Worthlessness without achievement.",
    contradictoryBehavior: "Celebrating others publicly while privately inventorying how they threaten your rank.",
    cost: "Loneliness at the top of a ladder no one else cares about.",
    category: "SELF",
    node: "self-worth",
    secondaryConflicts: ["EGO/status", "SOCIETY/success"],
    universalityScore: 0.91,
    depthScore: 0.84,
    noveltyScore: 0.5,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["envy", "emptiness"],
    domains: ["career", "identity"],
    lenses: ["psychological", "stoic"],
  },
  {
    statement: "Guilt can become a substitute for change — feeling bad enough that no action is required.",
    observation: "Chronic guilt soothes the conscience without altering the pattern; it is remorse as anesthesia.",
    desire: "Absolution without the work of repair.",
    hiddenFear: "That repair would reveal how much damage was done.",
    contradictoryBehavior: "Apologizing repeatedly while repeating the offense.",
    cost: "Erosion of trust; self-image as the remorseful one instead of the changed one.",
    category: "SELF",
    node: "guilt",
    secondaryConflicts: ["CHARACTER/responsibility", "RELATIONSHIPS/forgiveness"],
    universalityScore: 0.88,
    depthScore: 0.85,
    noveltyScore: 0.64,
    recognitionScore: 0.86,
    status: "approved",
    emotions: ["guilt", "avoidance"],
    domains: ["character", "relationships"],
    lenses: ["moral", "psychological"],
  },
  {
    statement: "Identity crisis is often an identity surplus — too many borrowed selves and no room for a chosen one.",
    observation: "People drown in roles and call the drowning a search for self.",
    desire: "A single coherent narrative that can say no.",
    hiddenFear: "That without roles there is nothing left.",
    contradictoryBehavior: "Collecting new identities when the old ones feel hollow.",
    cost: "Fragmentation; inability to commit because commitment kills options.",
    category: "SELF",
    node: "identity",
    secondaryConflicts: ["SOCIETY/conformity", "ATTACHMENT/identity"],
    universalityScore: 0.87,
    depthScore: 0.83,
    noveltyScore: 0.7,
    recognitionScore: 0.84,
    status: "approved",
    emotions: ["confusion", "anxiety"],
    domains: ["identity", "culture"],
    lenses: ["existential", "cultural"],
  },
  {
    statement: "We mistreat our future selves because they cannot speak in the present tense.",
    observation: "Sleep, savings, and relationships are raided by a present self that treats tomorrow as a stranger.",
    desire: "Relief now.",
    hiddenFear: "That future pain is abstract and therefore unreal.",
    contradictoryBehavior: "Writing letters to future you while ignoring today's body.",
    cost: "A bill that always comes due, with interest.",
    category: "SELF",
    node: "self-deception",
    secondaryConflicts: ["CHARACTER/discipline", "DESIRE/instant-gratification"],
    universalityScore: 0.9,
    depthScore: 0.8,
    noveltyScore: 0.57,
    recognitionScore: 0.89,
    status: "approved",
    emotions: ["avoidance", "guilt"],
    domains: ["habits", "health"],
    lenses: ["behavioral", "stoic"],
  },
  {
    statement: "The ego does not want to be happy — it wants to be right, and it will trade peace for that victory.",
    observation: "Arguments that should end keep going because the stake is not the topic but the self's rank in the room.",
    desire: "To occupy the high ground permanently.",
    hiddenFear: "Being diminished into irrelevance.",
    contradictoryBehavior: "Claiming to seek understanding while preparing the next rebuttal.",
    cost: "Damaged intimacy; a mind that cannot rest.",
    category: "EGO",
    node: "need-to-be-right",
    secondaryConflicts: ["RELATIONSHIPS/boundaries", "CHARACTER/honesty"],
    universalityScore: 0.93,
    depthScore: 0.87,
    noveltyScore: 0.52,
    recognitionScore: 0.92,
    status: "approved",
    emotions: ["anger", "pride"],
    domains: ["relationships", "work"],
    lenses: ["psychological", "stoic"], exceptional: true,
  },
  {
    statement: "Status is a moving target that promises arrival and delivers another race.",
    observation: "Each promotion resets the peer group; the feeling of enough is postponed indefinitely.",
    desire: "Recognition that finally settles the question of worth.",
    hiddenFear: "Invisibility.",
    contradictoryBehavior: "Dismissing status games while carefully tracking likes, titles, and invites.",
    cost: "Life spent climbing a ladder leaned against the wrong wall.",
    category: "EGO",
    node: "status",
    secondaryConflicts: ["SOCIETY/success", "DESIRE/ambition"],
    universalityScore: 0.9,
    depthScore: 0.8,
    noveltyScore: 0.45,
    recognitionScore: 0.91,
    status: "approved",
    emotions: ["craving", "anxiety"],
    domains: ["career", "society"],
    lenses: ["cultural", "buddhist"],
  },
  {
    statement: "Validation from others is a drug with a shortening half-life.",
    observation: "Praise that once lasted weeks now lasts hours; the nervous system adapts and demands a larger dose.",
    desire: "External proof that one exists and matters.",
    hiddenFear: "That without mirrors there is no self.",
    contradictoryBehavior: "Proclaiming independence while refreshing metrics.",
    cost: "Outsourcing emotional regulation to an audience that is busy.",
    category: "EGO",
    node: "validation",
    secondaryConflicts: ["SOCIETY/social-media", "SELF/self-worth"],
    universalityScore: 0.92,
    depthScore: 0.81,
    noveltyScore: 0.48,
    recognitionScore: 0.94,
    status: "approved",
    emotions: ["hunger", "emptiness"],
    domains: ["social-media", "identity"],
    lenses: ["psychological", "cultural"],
  },
  {
    statement: "Envy is desire wearing a mask of moral judgment.",
    observation: "We rarely admit envy; we reframe the envied as undeserving so longing becomes righteousness.",
    desire: "To possess without admitting hunger.",
    hiddenFear: "That someone else's gain reveals our lack.",
    contradictoryBehavior: "Congratulating while privately hoping they stumble.",
    cost: "Bitterness that poisons joy and friendship.",
    category: "EGO",
    node: "envy",
    secondaryConflicts: ["DESIRE/ambition", "SELF/self-worth"],
    universalityScore: 0.91,
    depthScore: 0.84,
    noveltyScore: 0.6,
    recognitionScore: 0.89,
    status: "approved",
    emotions: ["envy", "resentment"],
    domains: ["relationships", "career"],
    lenses: ["psychological", "moral"],
  },
  {
    statement: "Comparison is a rigged contest: we compare our insides to other people's outsides.",
    observation: "People measure their private chaos against curated highlights and conclude they are uniquely broken.",
    desire: "A fair ranking that confirms we are ahead.",
    hiddenFear: "Being behind permanently.",
    contradictoryBehavior: "Limiting social media for mental health then checking it in private tabs.",
    cost: "Chronic inadequacy; inability to celebrate others.",
    category: "EGO",
    node: "comparison",
    secondaryConflicts: ["SOCIETY/social-media", "SELF/insecurity"],
    universalityScore: 0.94,
    depthScore: 0.78,
    noveltyScore: 0.35,
    recognitionScore: 0.95,
    status: "approved",
    emotions: ["shame", "anxiety"],
    domains: ["social-media", "identity"],
    lenses: ["cultural", "psychological"],
  },
  {
    statement: "Superiority is loneliness with a trophy.",
    observation: "Feeling above others creates distance that feels like safety until it feels like exile.",
    desire: "Protection from being ordinary.",
    hiddenFear: "Needing people who you have trained yourself to disdain.",
    contradictoryBehavior: "Seeking community while ranking everyone in it.",
    cost: "No peers — only audiences and inferiors.",
    category: "EGO",
    node: "superiority",
    secondaryConflicts: ["RELATIONSHIPS/friendship", "SELF/self-worth"],
    universalityScore: 0.85,
    depthScore: 0.86,
    noveltyScore: 0.68,
    recognitionScore: 0.82,
    status: "approved",
    emotions: ["pride", "loneliness"],
    domains: ["character", "relationships"],
    lenses: ["existential", "psychological"],
  },
  {
    statement: "Resentment is a debt we keep trying to collect from people who don't know they owe us.",
    observation: "Unspoken expectations harden into silent invoices; the other person never received the bill.",
    desire: "Recognition of our sacrifice.",
    hiddenFear: "That our giving was voluntary and therefore unpayable.",
    contradictoryBehavior: "Saying it's fine while stocking evidence for a future trial.",
    cost: "Relationships become courtrooms; intimacy dies.",
    category: "EGO",
    node: "resentment",
    secondaryConflicts: ["RELATIONSHIPS/boundaries", "ATTACHMENT/expectations"],
    universalityScore: 0.9,
    depthScore: 0.88,
    noveltyScore: 0.66,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["resentment", "hurt"],
    domains: ["relationships", "family"],
    lenses: ["psychological"], exceptional: true,
  },
  {
    statement: "Pride refuses help because accepting help would rewrite the story of the self as capable alone.",
    observation: "People drown near shore rather than signal weakness to witnesses.",
    desire: "Autonomy as proof of worth.",
    hiddenFear: "Dependency equals humiliation.",
    contradictoryBehavior: "Advising others to ask for help while refusing it ourselves.",
    cost: "Preventable failure; isolation in crises.",
    category: "EGO",
    node: "pride",
    secondaryConflicts: ["FEAR/judgment", "CHARACTER/responsibility"],
    universalityScore: 0.88,
    depthScore: 0.82,
    noveltyScore: 0.5,
    recognitionScore: 0.87,
    status: "approved",
    emotions: ["pride", "fear"],
    domains: ["work", "health"],
    lenses: ["stoic", "psychological"],
  },
  {
    statement: "Pleasure pursued as a life strategy becomes a treadmill that raises the dose and lowers the return.",
    observation: "What once thrilled becomes baseline; boredom is misread as a need for more intensity.",
    desire: "A feeling that finally lasts.",
    hiddenFear: "An empty interior that no stimulus can fill.",
    contradictoryBehavior: "Calling it self-care while escalating consumption.",
    cost: "Tolerance, dependency, and a shrinking capacity for quiet joy.",
    category: "DESIRE",
    node: "pleasure",
    secondaryConflicts: ["CHARACTER/self-control", "SUFFERING/meaninglessness"],
    universalityScore: 0.89,
    depthScore: 0.85,
    noveltyScore: 0.48,
    recognitionScore: 0.88,
    status: "approved",
    emotions: ["craving", "emptiness"],
    domains: ["addiction", "lifestyle"],
    lenses: ["buddhist", "psychological"],
  },
  {
    statement: "Greed is fear of future scarcity wearing the language of ambition.",
    observation: "Accumulation continues past need because the nervous system never updates enough.",
    desire: "Safety stored as surplus.",
    hiddenFear: "Being left without options when winter comes.",
    contradictoryBehavior: "Hoarding while preaching abundance.",
    cost: "Relationships and time sacrificed to a bunker that never feels full.",
    category: "DESIRE",
    node: "greed",
    secondaryConflicts: ["FEAR/uncertainty", "SOCIETY/money"],
    universalityScore: 0.86,
    depthScore: 0.83,
    noveltyScore: 0.55,
    recognitionScore: 0.84,
    status: "approved",
    emotions: ["fear", "hunger"],
    domains: ["money", "security"],
    lenses: ["psychological", "economic"],
  },
  {
    statement: "Craving is not about the object — it is about the temporary relief from wanting.",
    observation: "The hit is the pause in wanting; when the pause ends, wanting returns louder.",
    desire: "Silence inside the wanting mind.",
    hiddenFear: "That wanting is the only thing animating us.",
    contradictoryBehavior: "Deleting apps then reinstalling them when the quiet gets loud.",
    cost: "Agency outsourced to the next urge.",
    category: "DESIRE",
    node: "craving",
    secondaryConflicts: ["CHARACTER/self-control", "SOCIETY/consumerism"],
    universalityScore: 0.91,
    depthScore: 0.9,
    noveltyScore: 0.62,
    recognitionScore: 0.89,
    status: "approved",
    emotions: ["craving", "restlessness"],
    domains: ["addiction", "attention"],
    lenses: ["buddhist", "psychological"], exceptional: true,
  },
  {
    statement: "Novelty addiction is grief for a present that never feels special enough.",
    observation: "People chase new cities, partners, aesthetics — not for discovery but to escape the ordinary of now.",
    desire: "A life that feels cinematic continuously.",
    hiddenFear: "That ordinary life is all there is.",
    contradictoryBehavior: "Romanticizing roots while booking the next escape.",
    cost: "Shallow roots; inability to deepen anywhere.",
    category: "DESIRE",
    node: "novelty",
    secondaryConflicts: ["ATTACHMENT/past", "SUFFERING/disappointment"],
    universalityScore: 0.84,
    depthScore: 0.81,
    noveltyScore: 0.7,
    recognitionScore: 0.83,
    status: "approved",
    emotions: ["restlessness", "boredom"],
    domains: ["lifestyle", "relationships"],
    lenses: ["existential", "cultural"],
  },
  {
    statement: "Consumption is often an attempt to purchase a feeling that only belonging can provide.",
    observation: "Shopping, upgrading, unboxing — brief belonging to a tribe of owners, then silence.",
    desire: "To feel included and current.",
    hiddenFear: "Being left behind culturally.",
    contradictoryBehavior: "Critiquing consumerism while tracking drops.",
    cost: "Debt, clutter, and a self defined by inventory.",
    category: "DESIRE",
    node: "consumption",
    secondaryConflicts: ["SOCIETY/consumerism", "EGO/status"],
    universalityScore: 0.88,
    depthScore: 0.79,
    noveltyScore: 0.5,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["longing", "emptiness"],
    domains: ["money", "culture"],
    lenses: ["cultural", "psychological"],
  },
  {
    statement: "Ambition becomes pathology when the future self is loved more than the present one.",
    observation: "People abuse today's body and relationships to feed a hypothetical person who may never thank them.",
    desire: "A redeemed future that justifies present suffering.",
    hiddenFear: "That without ambition the present is meaningless.",
    contradictoryBehavior: "Posting about balance while sleeping four hours.",
    cost: "A resume that outlives the relationships that made life worth living.",
    category: "DESIRE",
    node: "ambition",
    secondaryConflicts: ["MEANING/purpose", "CHARACTER/discipline"],
    universalityScore: 0.9,
    depthScore: 0.87,
    noveltyScore: 0.58,
    recognitionScore: 0.88,
    status: "approved",
    emotions: ["drive", "guilt"],
    domains: ["career", "health"],
    lenses: ["existential", "stoic"],
  },
  {
    statement: "Instant gratification trains the mind to treat waiting as injury.",
    observation: "When everything arrives now, patience feels like deprivation rather than a skill.",
    desire: "Frictionless life.",
    hiddenFear: "That delayed rewards will never come.",
    contradictoryBehavior: "Planning long-term goals while abandoning them at the first hard week.",
    cost: "Atrophy of grit; projects that never compound.",
    category: "DESIRE",
    node: "instant-gratification",
    secondaryConflicts: ["CHARACTER/patience", "CHARACTER/discipline"],
    universalityScore: 0.92,
    depthScore: 0.8,
    noveltyScore: 0.42,
    recognitionScore: 0.93,
    status: "approved",
    emotions: ["impatience", "frustration"],
    domains: ["attention", "habits"],
    lenses: ["psychological", "cultural"],
  },
  {
    statement: "We confuse wanting more options with wanting freedom — then drown in the menu.",
    observation: "Choice overload is sold as liberty; the nervous system experiences it as threat.",
    desire: "The perfect choice that cannot be regretted.",
    hiddenFear: "Commitment that closes doors.",
    contradictoryBehavior: "Researching endlessly while living none of the options.",
    cost: "Paralysis; a life deferred to comparison spreadsheets.",
    category: "DESIRE",
    node: "novelty",
    secondaryConflicts: ["FEAR/uncertainty", "ATTACHMENT/expectations"],
    universalityScore: 0.86,
    depthScore: 0.82,
    noveltyScore: 0.67,
    recognitionScore: 0.85,
    status: "approved",
    emotions: ["anxiety", "overwhelm"],
    domains: ["decision-making", "lifestyle"],
    lenses: ["behavioral", "existential"],
  },
  {
    statement: "Fear of rejection makes us reject ourselves first so no one else gets the chance.",
    observation: "Preemptive withdrawal, ghosting our own desires, shrinking before the room can.",
    desire: "Safety from the sting of being unwanted.",
    hiddenFear: "Confirmation that we are unlovable.",
    contradictoryBehavior: "Craving closeness while sabotaging invitations.",
    cost: "A life of almosts; loneliness attributed to bad luck.",
    category: "FEAR",
    node: "rejection",
    secondaryConflicts: ["SELF/insecurity", "RELATIONSHIPS/love"],
    universalityScore: 0.93,
    depthScore: 0.86,
    noveltyScore: 0.5,
    recognitionScore: 0.92,
    status: "approved",
    emotions: ["fear", "shame"],
    domains: ["relationships", "dating"],
    lenses: ["psychological"], exceptional: true,
  },
  {
    statement: "Fear of failure often disguises a fear of being seen trying.",
    observation: "If you never fully try, failure can be blamed on lack of effort — ego stays intact.",
    desire: "A story where potential remains infinite.",
    hiddenFear: "A public verdict on limited ability.",
    contradictoryBehavior: "Dreaming loudly and preparing quietly — or not at all.",
    cost: "Potential as identity; achievement as threat.",
    category: "FEAR",
    node: "failure",
    secondaryConflicts: ["EGO/pride", "SELF/self-worth"],
    universalityScore: 0.91,
    depthScore: 0.85,
    noveltyScore: 0.55,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["fear", "pride"],
    domains: ["career", "creativity"],
    lenses: ["psychological", "stoic"],
  },
  {
    statement: "Abandonment fear turns love into surveillance.",
    observation: "Checking, testing, clinging — affection becomes a system for preventing exit.",
    desire: "A bond that cannot leave.",
    hiddenFear: "Being left the way we once were.",
    contradictoryBehavior: "Demanding space while panicking when it's given.",
    cost: "Partners feel hunted; the feared ending arrives by self-fulfilling prophecy.",
    category: "FEAR",
    node: "abandonment",
    secondaryConflicts: ["ATTACHMENT/people", "RELATIONSHIPS/dependency"],
    universalityScore: 0.89,
    depthScore: 0.88,
    noveltyScore: 0.52,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["panic", "longing"],
    domains: ["relationships", "attachment"],
    lenses: ["psychological"],
  },
  {
    statement: "Death anxiety often hides inside productivity culture as a refusal to feel time.",
    observation: "Busyness numbs mortality; stillness lets death into the room.",
    desire: "A life so full it cannot end.",
    hiddenFear: "Oblivion and unfinished meaning.",
    contradictoryBehavior: "Talking about legacy while avoiding funerals and aging parents.",
    cost: "A crowded calendar and an unexamined life.",
    category: "FEAR",
    node: "death",
    secondaryConflicts: ["MEANING/mortality", "MEANING/time"],
    universalityScore: 0.87,
    depthScore: 0.9,
    noveltyScore: 0.65,
    recognitionScore: 0.84,
    status: "approved",
    emotions: ["anxiety", "denial"],
    domains: ["meaning", "lifestyle"],
    lenses: ["existential", "stoic"], exceptional: true,
  },
  {
    statement: "Uncertainty intolerance makes people invent false certainty and call it intuition.",
    observation: "Ambiguity is rewritten into narratives or rigid plans that feel safer than not knowing.",
    desire: "A map that removes surprise.",
    hiddenFear: "Powerlessness in an unpredictable world.",
    contradictoryBehavior: "Asking for advice then discarding anything that increases ambiguity.",
    cost: "Brittle decisions; hostility to new information.",
    category: "FEAR",
    node: "uncertainty",
    secondaryConflicts: ["ATTACHMENT/beliefs", "CHARACTER/courage"],
    universalityScore: 0.9,
    depthScore: 0.84,
    noveltyScore: 0.6,
    recognitionScore: 0.87,
    status: "approved",
    emotions: ["anxiety", "control"],
    domains: ["decision-making", "politics"],
    lenses: ["psychological", "existential"],
  },
  {
    statement: "Fear of judgment trains us to live as a press conference.",
    observation: "Every choice is auditioned for an imaginary audience before it is lived.",
    desire: "Universal approval.",
    hiddenFear: "Exile from the tribe.",
    contradictoryBehavior: "Claiming not to care what people think while crafting the image carefully.",
    cost: "Self-estrangement; creativity reduced to brand management.",
    category: "FEAR",
    node: "judgment",
    secondaryConflicts: ["EGO/validation", "SOCIETY/conformity"],
    universalityScore: 0.92,
    depthScore: 0.82,
    noveltyScore: 0.48,
    recognitionScore: 0.93,
    status: "approved",
    emotions: ["shame", "anxiety"],
    domains: ["social", "creativity"],
    lenses: ["cultural", "psychological"],
  },
  {
    statement: "Fear of change protects a familiar misery against an unfamiliar hope.",
    observation: "People stay because the devil they know has a schedule; growth has no itinerary.",
    desire: "Safety of the known pattern.",
    hiddenFear: "That change will reveal we cannot adapt.",
    contradictoryBehavior: "Consuming transformation content while changing nothing structural.",
    cost: "Years donated to a life that only half fits.",
    category: "FEAR",
    node: "change",
    secondaryConflicts: ["ATTACHMENT/past", "CHARACTER/courage"],
    universalityScore: 0.9,
    depthScore: 0.83,
    noveltyScore: 0.5,
    recognitionScore: 0.91,
    status: "approved",
    emotions: ["fear", "inertia"],
    domains: ["life-transitions", "habits"],
    lenses: ["psychological", "existential"],
  },
  {
    statement: "Loneliness can become an identity that rejects the very connection it claims to want.",
    observation: "After enough isolation, closeness feels invasive; the lonely person defends the solitude that hurts them.",
    desire: "Company that requires no vulnerability.",
    hiddenFear: "Being known and still left.",
    contradictoryBehavior: "Complaining of loneliness while canceling plans.",
    cost: "A sealed room with a window to the world.",
    category: "FEAR",
    node: "loneliness",
    secondaryConflicts: ["RELATIONSHIPS/friendship", "SELF/shame"],
    universalityScore: 0.88,
    depthScore: 0.87,
    noveltyScore: 0.63,
    recognitionScore: 0.88,
    status: "approved",
    emotions: ["loneliness", "ambivalence"],
    domains: ["relationships", "mental-health"],
    lenses: ["psychological", "existential"],
  },
  {
    statement: "We cling to people not always from love, but from fear of who we are without them.",
    observation: "Attachment can be a prosthesis for an incomplete self; separation feels like amputation.",
    desire: "A self that is whole alone and still chooses together.",
    hiddenFear: "Emptiness when the mirror leaves.",
    contradictoryBehavior: "Saying I love you when the accurate sentence is I need you to exist.",
    cost: "Relationships that cannot breathe; partners who feel used as scaffolding.",
    category: "ATTACHMENT",
    node: "people",
    secondaryConflicts: ["RELATIONSHIPS/dependency", "SELF/identity"],
    universalityScore: 0.91,
    depthScore: 0.89,
    noveltyScore: 0.55,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["fear", "longing"],
    domains: ["relationships", "attachment"],
    lenses: ["psychological"], exceptional: true,
  },
  {
    statement: "Memories become prisons when we mistreat nostalgia as a destination rather than a visit.",
    observation: "People curate a golden past and convict the present for failing to match a highlight reel.",
    desire: "To return to a feeling that may never have been as pure as remembered.",
    hiddenFear: "That the best is behind us.",
    contradictoryBehavior: "Saying live in the present while scrolling old photos for hours.",
    cost: "Inability to build new peak experiences; bitterness toward time.",
    category: "ATTACHMENT",
    node: "memories",
    secondaryConflicts: ["MEANING/time", "SUFFERING/regret"],
    universalityScore: 0.87,
    depthScore: 0.84,
    noveltyScore: 0.58,
    recognitionScore: 0.88,
    status: "approved",
    emotions: ["nostalgia", "grief"],
    domains: ["aging", "identity"],
    lenses: ["existential", "psychological"],
  },
  {
    statement: "Possessions accumulate as emotional sandbags against a flood that never comes — or already did.",
    observation: "Clutter is often unfinished grief and deferred decisions wearing the shape of objects.",
    desire: "Control through ownership.",
    hiddenFear: "Being stripped of identity markers.",
    contradictoryBehavior: "Buying organizers for things we refuse to release.",
    cost: "A home that cannot host life; attention trapped in maintenance.",
    category: "ATTACHMENT",
    node: "possessions",
    secondaryConflicts: ["DESIRE/consumption", "FEAR/uncertainty"],
    universalityScore: 0.84,
    depthScore: 0.8,
    noveltyScore: 0.6,
    recognitionScore: 0.85,
    status: "approved",
    emotions: ["anxiety", "attachment"],
    domains: ["home", "money"],
    lenses: ["psychological", "buddhist"],
  },
  {
    statement: "Beliefs we refuse to update become identity armor — and armor eventually becomes a cage.",
    observation: "Changing a belief threatens belonging to the tribe that shared it; so people defend maps that no longer match terrain.",
    desire: "Coherence and tribal membership.",
    hiddenFear: "Exile for updating.",
    contradictoryBehavior: "Praising open-mindedness while punishing nuance in our own camp.",
    cost: "A mind that cannot learn; relationships that require shared delusions.",
    category: "ATTACHMENT",
    node: "beliefs",
    secondaryConflicts: ["EGO/need-to-be-right", "SOCIETY/conformity"],
    universalityScore: 0.9,
    depthScore: 0.88,
    noveltyScore: 0.62,
    recognitionScore: 0.89,
    status: "approved",
    emotions: ["fear", "pride"],
    domains: ["politics", "religion", "identity"],
    lenses: ["epistemic", "psychological"], exceptional: true,
  },
  {
    statement: "We attach to identities the way addicts attach to substances — because they regulate feeling.",
    observation: "Titles, aesthetics, diagnoses, fandoms — all can become chemical substitutes for self-knowledge.",
    desire: "A stable story that reduces anxiety.",
    hiddenFear: "Formlessness.",
    contradictoryBehavior: "Rebranding constantly while claiming authenticity.",
    cost: "Growth requires identity death that feels like actual death.",
    category: "ATTACHMENT",
    node: "identity",
    secondaryConflicts: ["SELF/identity", "EGO/status"],
    universalityScore: 0.88,
    depthScore: 0.86,
    noveltyScore: 0.65,
    recognitionScore: 0.86,
    status: "approved",
    emotions: ["anxiety", "attachment"],
    domains: ["identity", "culture"],
    lenses: ["psychological", "existential"],
  },
  {
    statement: "Status attachment makes demotion feel like death even when nothing vital was lost.",
    observation: "A title change can devastate more than a real loss because rank was load-bearing for the ego.",
    desire: "Permanent elevation.",
    hiddenFear: "Falling into the crowd.",
    contradictoryBehavior: "Saying titles don't matter while checking org charts.",
    cost: "Risk-aversion; cruelty toward those below to secure the rung.",
    category: "ATTACHMENT",
    node: "status",
    secondaryConflicts: ["EGO/status", "SOCIETY/success"],
    universalityScore: 0.85,
    depthScore: 0.81,
    noveltyScore: 0.55,
    recognitionScore: 0.84,
    status: "approved",
    emotions: ["fear", "shame"],
    domains: ["career", "hierarchy"],
    lenses: ["cultural", "psychological"],
  },
  {
    statement: "Attachment to the past is often unfinished mourning disguised as loyalty.",
    observation: "Keeping everything the same becomes a ritual for people who are gone or versions of ourselves that died.",
    desire: "To not betray what was.",
    hiddenFear: "That moving on erases meaning.",
    contradictoryBehavior: "Encouraging others to heal while museum-keeping our own wounds.",
    cost: "A present that is only an annex to a shrine.",
    category: "ATTACHMENT",
    node: "past",
    secondaryConflicts: ["SUFFERING/grief", "MEANING/time"],
    universalityScore: 0.86,
    depthScore: 0.87,
    noveltyScore: 0.6,
    recognitionScore: 0.87,
    status: "approved",
    emotions: ["grief", "loyalty"],
    domains: ["grief", "family"],
    lenses: ["psychological", "existential"],
  },
  {
    statement: "Expectations are premeditated resentments waiting for reality to fail them.",
    observation: "Unnegotiated expectations turn partners and colleagues into perpetual debtors.",
    desire: "A world that behaves according to our private script.",
    hiddenFear: "That without expectations we will be taken advantage of.",
    contradictoryBehavior: "Calling them standards while never stating them aloud.",
    cost: "Chronic disappointment; others walking on eggshells.",
    category: "ATTACHMENT",
    node: "expectations",
    secondaryConflicts: ["EGO/resentment", "RELATIONSHIPS/boundaries"],
    universalityScore: 0.91,
    depthScore: 0.85,
    noveltyScore: 0.58,
    recognitionScore: 0.91,
    status: "approved",
    emotions: ["disappointment", "resentment"],
    domains: ["relationships", "work"],
    lenses: ["psychological", "stoic"],
  },
  {
    statement: "Love often begins as recognition and decays into management.",
    observation: "Early love sees; later love tries to control outcomes, schedules, and the other person's growth.",
    desire: "A bond that stays as vivid as the beginning.",
    hiddenFear: "That without management, love will leave.",
    contradictoryBehavior: "Saying I want you to be free while tracking every deviation.",
    cost: "Partners feel owned; passion replaced by logistics and suspicion.",
    category: "RELATIONSHIPS",
    node: "love",
    secondaryConflicts: ["ATTACHMENT/people", "FEAR/abandonment"],
    universalityScore: 0.9,
    depthScore: 0.86,
    noveltyScore: 0.6,
    recognitionScore: 0.89,
    status: "approved",
    emotions: ["love", "fear"],
    domains: ["romance", "marriage"],
    lenses: ["psychological", "existential"],
  },
  {
    statement: "Dependency disguises itself as devotion until the devoted person cannot breathe alone.",
    observation: "What is praised as loyalty can be an inability to self-regulate without the other.",
    desire: "Fusion that ends loneliness.",
    hiddenFear: "Autonomous emptiness.",
    contradictoryBehavior: "Calling neediness romance while resenting the burden of being needed.",
    cost: "Two incomplete people making one fragile unit.",
    category: "RELATIONSHIPS",
    node: "dependency",
    secondaryConflicts: ["ATTACHMENT/people", "SELF/identity"],
    universalityScore: 0.88,
    depthScore: 0.87,
    noveltyScore: 0.55,
    recognitionScore: 0.88,
    status: "approved",
    emotions: ["need", "anxiety"],
    domains: ["romance", "attachment"],
    lenses: ["psychological"],
  },
  {
    statement: "Betrayal hurts most where trust was used as a shortcut past discernment.",
    observation: "People often 'trust' to avoid the discomfort of verifying character slowly.",
    desire: "Safety without vigilance.",
    hiddenFear: "That careful love is not romantic.",
    contradictoryBehavior: "Ignoring red flags then calling the outcome sudden.",
    cost: "Cynicism that poisons future bonds; or naivete that repeats.",
    category: "RELATIONSHIPS",
    node: "betrayal",
    secondaryConflicts: ["FEAR/abandonment", "CHARACTER/honesty"],
    universalityScore: 0.87,
    depthScore: 0.84,
    noveltyScore: 0.62,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["shock", "grief"],
    domains: ["romance", "friendship"],
    lenses: ["psychological", "moral"], exceptional: true,
  },
  {
    statement: "Family loyalty can demand that we betray ourselves to keep the system calm.",
    observation: "Roles assigned in childhood persist; speaking truth is treated as violence against the family myth.",
    desire: "Belonging without self-erasure.",
    hiddenFear: "Exile from origin.",
    contradictoryBehavior: "Building adult lives while still auditioning for parental approval.",
    cost: "Adult children; repeating patterns in new homes.",
    category: "RELATIONSHIPS",
    node: "family",
    secondaryConflicts: ["SELF/authenticity", "ATTACHMENT/expectations"],
    universalityScore: 0.91,
    depthScore: 0.89,
    noveltyScore: 0.52,
    recognitionScore: 0.92,
    status: "approved",
    emotions: ["guilt", "longing"],
    domains: ["family", "identity"],
    lenses: ["psychological", "cultural"], exceptional: true,
  },
  {
    statement: "Friendship dies quietly when convenience replaces curiosity.",
    observation: "People keep each other as contacts while the living interest that made friendship evaporates.",
    desire: "Bonds that survive without constant performance.",
    hiddenFear: "That we are only useful, not loved.",
    contradictoryBehavior: "Posting about chosen family while not answering messages.",
    cost: "A social graph without witnesses to your life.",
    category: "RELATIONSHIPS",
    node: "friendship",
    secondaryConflicts: ["SOCIETY/social-media", "FEAR/loneliness"],
    universalityScore: 0.89,
    depthScore: 0.8,
    noveltyScore: 0.58,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["loneliness", "nostalgia"],
    domains: ["friendship", "modern-life"],
    lenses: ["cultural", "psychological"],
  },
  {
    statement: "Marriage often fails at the transition from romance to shared reality — not because love dies, but because skills were never taught.",
    observation: "Culture trains attraction; it undertrains repair, boredom tolerance, and joint meaning-making.",
    desire: "A partnership that can survive Tuesday.",
    hiddenFear: "That ordinary days mean the magic was fake.",
    contradictoryBehavior: "Consuming wedding content while avoiding conflict skills.",
    cost: "Serial intensity or silent coexistence.",
    category: "RELATIONSHIPS",
    node: "marriage",
    secondaryConflicts: ["ATTACHMENT/expectations", "CHARACTER/patience"],
    universalityScore: 0.86,
    depthScore: 0.83,
    noveltyScore: 0.55,
    recognitionScore: 0.87,
    status: "approved",
    emotions: ["disappointment", "love"],
    domains: ["marriage", "family"],
    lenses: ["psychological", "cultural"],
  },
  {
    statement: "Forgiveness without boundaries is a subscription to being hurt again.",
    observation: "People confuse forgiveness with access; mercy becomes a loophole for the unrepentant.",
    desire: "Peace without naivete.",
    hiddenFear: "That boundaries make us unloving.",
    contradictoryBehavior: "Forgiving publicly while privately rehearsing the wound — or the opposite.",
    cost: "Either bitterness or repeated injury.",
    category: "RELATIONSHIPS",
    node: "forgiveness",
    secondaryConflicts: ["RELATIONSHIPS/boundaries", "CHARACTER/integrity"],
    universalityScore: 0.9,
    depthScore: 0.88,
    noveltyScore: 0.65,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["ambivalence", "hurt"],
    domains: ["relationships", "healing"],
    lenses: ["moral", "psychological"], exceptional: true,
  },
  {
    statement: "Boundaries are not walls against love — they are the architecture that makes love inhabitable.",
    observation: "Without boundaries, closeness becomes intrusion and generosity becomes resentment.",
    desire: "Connection with self-respect.",
    hiddenFear: "That saying no will end belonging.",
    contradictoryBehavior: "Teaching boundaries online while folding in real rooms.",
    cost: "Either isolation or self-abandonment.",
    category: "RELATIONSHIPS",
    node: "boundaries",
    secondaryConflicts: ["SELF/self-worth", "EGO/resentment"],
    universalityScore: 0.92,
    depthScore: 0.84,
    noveltyScore: 0.45,
    recognitionScore: 0.93,
    status: "approved",
    emotions: ["fear", "relief"],
    domains: ["relationships", "work"],
    lenses: ["psychological"],
  },
  {
    statement: "Discipline is choosing what you want most over what you want now — repeatedly, without applause.",
    observation: "Most people want the outcomes of discipline while negotiating exceptions every day.",
    desire: "A self that can be trusted with its own goals.",
    hiddenFear: "That without mood we have no motivation — and mood is unreliable.",
    contradictoryBehavior: "Buying planners and courses instead of doing the next hard rep.",
    cost: "A life of almost-started transformations.",
    category: "CHARACTER",
    node: "discipline",
    secondaryConflicts: ["DESIRE/instant-gratification", "CHARACTER/self-control"],
    universalityScore: 0.9,
    depthScore: 0.8,
    noveltyScore: 0.4,
    recognitionScore: 0.91,
    status: "approved",
    emotions: ["struggle", "pride"],
    domains: ["habits", "work"],
    lenses: ["stoic", "behavioral"],
  },
  {
    statement: "Courage is not fearlessness — it is acting while the body votes no.",
    observation: "People wait to feel brave; bravery is often the byproduct of action, not the prerequisite.",
    desire: "To move despite the alarm.",
    hiddenFear: "That action will confirm danger.",
    contradictoryBehavior: "Consuming courage quotes while avoiding the phone call.",
    cost: "A shrinking territory of life.",
    category: "CHARACTER",
    node: "courage",
    secondaryConflicts: ["FEAR/judgment", "FEAR/failure"],
    universalityScore: 0.91,
    depthScore: 0.82,
    noveltyScore: 0.42,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["fear", "resolve"],
    domains: ["growth", "leadership"],
    lenses: ["stoic", "existential"],
  },
  {
    statement: "Honesty with others is rare; honesty with ourselves is rarer — and usually arrives late.",
    observation: "We tell partial truths that protect self-image and call it kindness or strategy.",
    desire: "To be seen as good without the cost of being true.",
    hiddenFear: "That full honesty would make us unlovable or unsuccessful.",
    contradictoryBehavior: "Demanding transparency from others while editing our own narratives.",
    cost: "Relationships built on negotiated fiction; a self that cannot be trusted.",
    category: "CHARACTER",
    node: "honesty",
    secondaryConflicts: ["SELF/self-deception", "EGO/pride"],
    universalityScore: 0.89,
    depthScore: 0.87,
    noveltyScore: 0.55,
    recognitionScore: 0.88,
    status: "approved",
    emotions: ["shame", "integrity"],
    domains: ["character", "relationships"],
    lenses: ["moral", "psychological"],
  },
  {
    statement: "Patience is the ability to suffer the gap between effort and result without inventing drama.",
    observation: "Impatience creates false emergencies that justify quitting or cheating the process.",
    desire: "Results on an emotional timeline.",
    hiddenFear: "That waiting means we chose wrong.",
    contradictoryBehavior: "Praising compound interest while yanking seedlings weekly.",
    cost: "Interrupted compounding; chronic restarting.",
    category: "CHARACTER",
    node: "patience",
    secondaryConflicts: ["DESIRE/instant-gratification", "FEAR/uncertainty"],
    universalityScore: 0.88,
    depthScore: 0.81,
    noveltyScore: 0.5,
    recognitionScore: 0.87,
    status: "approved",
    emotions: ["impatience", "anxiety"],
    domains: ["habits", "career"],
    lenses: ["stoic", "behavioral"],
  },
  {
    statement: "Responsibility is the decision to be the author of your response even when you are not the author of the event.",
    observation: "Victimhood can be factually accurate and still strategically useless as a permanent identity.",
    desire: "Agency without denial of harm.",
    hiddenFear: "That accepting responsibility absolves the guilty.",
    contradictoryBehavior: "Demanding accountability from systems while exempting the self.",
    cost: "Powerlessness as a lifestyle; bitterness as fuel that runs out.",
    category: "CHARACTER",
    node: "responsibility",
    secondaryConflicts: ["SUFFERING/unfairness", "SELF/guilt"],
    universalityScore: 0.9,
    depthScore: 0.88,
    noveltyScore: 0.58,
    recognitionScore: 0.89,
    status: "approved",
    emotions: ["anger", "agency"],
    domains: ["character", "healing"],
    lenses: ["stoic", "existential"], exceptional: true,
  },
  {
    statement: "Temptation is not defeated by hatred of the object but by a clearer love of the life it would steal.",
    observation: "White-knuckle resistance fails when the alternative vision is vague.",
    desire: "A stronger why than the urge.",
    hiddenFear: "That desire is stronger than character.",
    contradictoryBehavior: "Relying on shame as a brake while keeping easy access to the trigger.",
    cost: "Cycles of binge and purge; identity as the struggler.",
    category: "CHARACTER",
    node: "temptation",
    secondaryConflicts: ["DESIRE/craving", "CHARACTER/self-control"],
    universalityScore: 0.87,
    depthScore: 0.85,
    noveltyScore: 0.66,
    recognitionScore: 0.86,
    status: "approved",
    emotions: ["craving", "resolve"],
    domains: ["addiction", "habits"],
    lenses: ["moral", "buddhist"],
  },
  {
    statement: "Integrity is expensive in the short term and cheap in the long term — the reverse of image management.",
    observation: "People trade integrity for speed, belonging, or profit, then pay with fragmentation.",
    desire: "A self that does not need two stories.",
    hiddenFear: "That integrity will cost opportunity others take.",
    contradictoryBehavior: "Posting values while negotiating exceptions privately.",
    cost: "A reputation that cannot survive daylight; self-contempt.",
    category: "CHARACTER",
    node: "integrity",
    secondaryConflicts: ["SOCIETY/success", "EGO/status"],
    universalityScore: 0.89,
    depthScore: 0.86,
    noveltyScore: 0.52,
    recognitionScore: 0.88,
    status: "approved",
    emotions: ["conflict", "resolve"],
    domains: ["work", "character"],
    lenses: ["moral", "stoic"],
  },
  {
    statement: "Self-control is not suppression forever — it is delaying the urge long enough for the wiser self to vote.",
    observation: "Urges peak and pass; people who always obey the peak never meet the pass.",
    desire: "A gap between stimulus and response.",
    hiddenFear: "That the gap means deprivation.",
    contradictoryBehavior: "Praising mindfulness while designing environments that maximize impulse.",
    cost: "A life run by the loudest momentary self.",
    category: "CHARACTER",
    node: "self-control",
    secondaryConflicts: ["DESIRE/instant-gratification", "DESIRE/craving"],
    universalityScore: 0.9,
    depthScore: 0.84,
    noveltyScore: 0.55,
    recognitionScore: 0.89,
    status: "approved",
    emotions: ["urge", "clarity"],
    domains: ["habits", "attention"],
    lenses: ["behavioral", "buddhist"],
  },
  {
    statement: "Loss reveals what we used the missing thing to avoid feeling.",
    observation: "Grief is not only about the person or object — it is about the structure of meaning that collapsed with them.",
    desire: "To restore the old architecture of meaning.",
    hiddenFear: "That a new architecture will feel like betrayal.",
    contradictoryBehavior: "Saying move on while refusing to rebuild.",
    cost: "Frozen time; identity as the bereaved.",
    category: "SUFFERING",
    node: "loss",
    secondaryConflicts: ["ATTACHMENT/people", "MEANING/purpose"],
    universalityScore: 0.9,
    depthScore: 0.9,
    noveltyScore: 0.58,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["grief", "emptiness"],
    domains: ["grief", "meaning"],
    lenses: ["existential", "psychological"], exceptional: true,
  },
  {
    statement: "Regret is the imagination punishing us for paths we can no longer walk.",
    observation: "The mind simulates counterfactuals as if they were still available, then charges interest.",
    desire: "A rewrite of the past.",
    hiddenFear: "That the chosen path permanently ruined us.",
    contradictoryBehavior: "Learning lessons verbally while rehearsing the wound nightly.",
    cost: "Present attention hijacked by closed doors.",
    category: "SUFFERING",
    node: "regret",
    secondaryConflicts: ["MEANING/time", "SELF/guilt"],
    universalityScore: 0.91,
    depthScore: 0.86,
    noveltyScore: 0.55,
    recognitionScore: 0.91,
    status: "approved",
    emotions: ["regret", "sadness"],
    domains: ["aging", "decisions"],
    lenses: ["existential", "psychological"],
  },
  {
    statement: "Disappointment is the collision between fantasy and evidence — and we often shoot the evidence.",
    observation: "People protect the fantasy by blaming people, timing, or fate rather than updating the model.",
    desire: "A world that matches the brochure.",
    hiddenFear: "That desire itself was foolish.",
    contradictoryBehavior: "Lowering standards in speech while raising them in secret.",
    cost: "Cynicism or repeated setups for the same fall.",
    category: "SUFFERING",
    node: "disappointment",
    secondaryConflicts: ["ATTACHMENT/expectations", "DESIRE/ambition"],
    universalityScore: 0.88,
    depthScore: 0.82,
    noveltyScore: 0.57,
    recognitionScore: 0.88,
    status: "approved",
    emotions: ["disappointment", "anger"],
    domains: ["relationships", "career"],
    lenses: ["psychological", "stoic"],
  },
  {
    statement: "Grief is love with nowhere to go — and the body keeps looking for the door.",
    observation: "Rituals, objects, and anniversaries are attempts to give love a temporary address.",
    desire: "Continued contact with what is gone.",
    hiddenFear: "Forgetting equals erasing.",
    contradictoryBehavior: "Wanting to heal while fearing that healing means the love was small.",
    cost: "Stuck mourning; or premature sealing that leaks later.",
    category: "SUFFERING",
    node: "grief",
    secondaryConflicts: ["ATTACHMENT/memories", "MEANING/mortality"],
    universalityScore: 0.92,
    depthScore: 0.91,
    noveltyScore: 0.45,
    recognitionScore: 0.93,
    status: "approved",
    emotions: ["grief", "love"],
    domains: ["grief", "family"],
    lenses: ["existential", "psychological"], exceptional: true,
  },
  {
    statement: "Frustration is blocked agency — the nervous system screaming that effort is not mapping to outcome.",
    observation: "Chronic frustration often means the goal, the method, or the timeline is mis-specified — not that the person is weak.",
    desire: "Visible progress.",
    hiddenFear: "Futile effort.",
    contradictoryBehavior: "Doubling down on the same approach louder.",
    cost: "Burnout; rage at the wrong targets.",
    category: "SUFFERING",
    node: "frustration",
    secondaryConflicts: ["DESIRE/ambition", "FEAR/failure"],
    universalityScore: 0.89,
    depthScore: 0.8,
    noveltyScore: 0.55,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["frustration", "anger"],
    domains: ["work", "habits"],
    lenses: ["psychological", "behavioral"],
  },
  {
    statement: "Meaninglessness is not the absence of activity — it is activity that cannot answer why.",
    observation: "Busy people can feel empty because motion was mistaken for purpose.",
    desire: "A why that survives boredom and success.",
    hiddenFear: "That there is no why.",
    contradictoryBehavior: "Adding more goals when the emptiness is qualitative, not quantitative.",
    cost: "Achievement that feels like ash; depression after victory.",
    category: "SUFFERING",
    node: "meaninglessness",
    secondaryConflicts: ["MEANING/purpose", "SOCIETY/success"],
    universalityScore: 0.9,
    depthScore: 0.9,
    noveltyScore: 0.55,
    recognitionScore: 0.89,
    status: "approved",
    emotions: ["emptiness", "anxiety"],
    domains: ["meaning", "career"],
    lenses: ["existential"], exceptional: true,
  },
  {
    statement: "The pain of unfairness is not only the injury — it is the insult to our need for a moral universe.",
    observation: "People can endure hardship that makes sense; random or unjust hardship threatens the story of order.",
    desire: "A cosmos that keeps score correctly.",
    hiddenFear: "That virtue is irrelevant to outcomes.",
    contradictoryBehavior: "Demanding justice for ourselves while rationalizing our own shortcuts.",
    cost: "Bitterness; or a collapse into cynicism that excuses cruelty.",
    category: "SUFFERING",
    node: "unfairness",
    secondaryConflicts: ["SOCIETY/power", "CHARACTER/integrity"],
    universalityScore: 0.88,
    depthScore: 0.87,
    noveltyScore: 0.6,
    recognitionScore: 0.88,
    status: "approved",
    emotions: ["outrage", "despair"],
    domains: ["justice", "work", "family"],
    lenses: ["moral", "existential"],
  },
  {
    statement: "Mortality is the deadline that makes meaning possible — and the terror that makes denial profitable.",
    observation: "Cultures sell immortality substitutes: brands, legacies, endless youth, infinite content.",
    desire: "Significance that outlasts the body.",
    hiddenFear: "Being forgotten.",
    contradictoryBehavior: "Memento mori tattoos next to calendars that refuse stillness.",
    cost: "A life optimized for afterimages rather than presence.",
    category: "MEANING",
    node: "mortality",
    secondaryConflicts: ["FEAR/death", "MEANING/legacy"],
    universalityScore: 0.89,
    depthScore: 0.92,
    noveltyScore: 0.58,
    recognitionScore: 0.87,
    status: "approved",
    emotions: ["awe", "fear"],
    domains: ["meaning", "culture"],
    lenses: ["existential", "stoic"], exceptional: true,
  },
  {
    statement: "Time feels scarce when we treat it as a resource to optimize rather than a medium to inhabit.",
    observation: "Productivity culture turns hours into inventory; presence becomes waste.",
    desire: "More time — usually meaning more accomplishment.",
    hiddenFear: "That an unoptimized hour was stolen from the future self.",
    contradictoryBehavior: "Scheduling rest as a performance metric.",
    cost: "A life remembered as a checklist.",
    category: "MEANING",
    node: "time",
    secondaryConflicts: ["SOCIETY/work", "DESIRE/ambition"],
    universalityScore: 0.9,
    depthScore: 0.85,
    noveltyScore: 0.6,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["anxiety", "urgency"],
    domains: ["lifestyle", "work"],
    lenses: ["existential", "cultural"],
  },
  {
    statement: "Purpose is discovered less by searching and more by committing long enough for meaning to accrue.",
    observation: "People wait for a lightning-bolt calling; most callings are built by devotion over time.",
    desire: "A clear vocation that removes doubt.",
    hiddenFear: "Wasting years on the wrong thing.",
    contradictoryBehavior: "Quitting at the boredom stage that precedes craft.",
    cost: "A museum of abandoned beginnings.",
    category: "MEANING",
    node: "purpose",
    secondaryConflicts: ["FEAR/failure", "CHARACTER/discipline"],
    universalityScore: 0.88,
    depthScore: 0.86,
    noveltyScore: 0.62,
    recognitionScore: 0.87,
    status: "approved",
    emotions: ["doubt", "devotion"],
    domains: ["career", "meaning"],
    lenses: ["existential", "stoic"],
  },
  {
    statement: "Legacy anxiety is ego trying to negotiate with death.",
    observation: "The need to be remembered can eclipse the need to be kind to the living.",
    desire: "A footprint that outlives us.",
    hiddenFear: "Oblivion.",
    contradictoryBehavior: "Neglecting present relationships to build monuments.",
    cost: "A name that is famous and a life that was thin.",
    category: "MEANING",
    node: "legacy",
    secondaryConflicts: ["EGO/status", "FEAR/death"],
    universalityScore: 0.85,
    depthScore: 0.84,
    noveltyScore: 0.65,
    recognitionScore: 0.84,
    status: "approved",
    emotions: ["ambition", "fear"],
    domains: ["meaning", "career"],
    lenses: ["existential", "psychological"],
  },
  {
    statement: "Faith, secular or sacred, is the decision to act as if meaning is real before proof arrives.",
    observation: "People demand certainty as a precondition for commitment; faith reverses the order.",
    desire: "Ground under the feet.",
    hiddenFear: "That commitment will be mocked by outcomes.",
    contradictoryBehavior: "Wanting the fruits of devotion without the risk of belief.",
    cost: "Perpetual hovering; no deep roots in any soil.",
    category: "MEANING",
    node: "faith",
    secondaryConflicts: ["FEAR/uncertainty", "CHARACTER/courage"],
    universalityScore: 0.84,
    depthScore: 0.88,
    noveltyScore: 0.6,
    recognitionScore: 0.83,
    status: "approved",
    emotions: ["doubt", "trust"],
    domains: ["religion", "meaning"],
    lenses: ["existential", "spiritual"],
  },
  {
    statement: "Gratitude is attention trained to notice what entitlement edits out.",
    observation: "The mind habituates to gifts and then invents new lacks; gratitude interrupts the edit.",
    desire: "Fullness without more acquisition.",
    hiddenFear: "That gratitude means settling.",
    contradictoryBehavior: "Gratitude journals next to envy scrolls.",
    cost: "A life that feels poor in the middle of plenty.",
    category: "MEANING",
    node: "gratitude",
    secondaryConflicts: ["EGO/envy", "DESIRE/consumption"],
    universalityScore: 0.9,
    depthScore: 0.8,
    noveltyScore: 0.4,
    recognitionScore: 0.91,
    status: "approved",
    emotions: ["gratitude", "humility"],
    domains: ["wellbeing", "lifestyle"],
    lenses: ["psychological", "spiritual"],
  },
  {
    statement: "Service escapes the self's echo chamber — which is why the ego resists it and the soul needs it.",
    observation: "Helping others reorganizes attention away from rumination; meaning increases as self-reference decreases.",
    desire: "To matter beyond the mirror.",
    hiddenFear: "Being used; or discovering the self is small.",
    contradictoryBehavior: "Performative charity that still centers the giver's image.",
    cost: "Either isolation in self-focus or hollow virtue signaling.",
    category: "MEANING",
    node: "service",
    secondaryConflicts: ["EGO/validation", "SOCIETY/status-signaling"],
    universalityScore: 0.86,
    depthScore: 0.85,
    noveltyScore: 0.58,
    recognitionScore: 0.85,
    status: "approved",
    emotions: ["purpose", "humility"],
    domains: ["community", "meaning"],
    lenses: ["moral", "spiritual"],
  },
  {
    statement: "Transcendence is not escape from the human — it is contact with something larger that makes the human bearable.",
    observation: "People seek transcendence in art, nature, love, God, flow — and counterfeit it in addiction and fame.",
    desire: "Relief from the small self.",
    hiddenFear: "That nothing larger exists.",
    contradictoryBehavior: "Mocking wonder while chasing peak experiences chemically.",
    cost: "Either cynicism or dependency on false peaks.",
    category: "MEANING",
    node: "transcendence",
    secondaryConflicts: ["DESIRE/pleasure", "SUFFERING/meaninglessness"],
    universalityScore: 0.84,
    depthScore: 0.9,
    noveltyScore: 0.65,
    recognitionScore: 0.82,
    status: "approved",
    emotions: ["awe", "longing"],
    domains: ["spirituality", "art"],
    lenses: ["existential", "spiritual"],
  },
  {
    statement: "Money problems are often meaning problems wearing a spreadsheet.",
    observation: "People use income as a proxy for safety, status, and freedom — then wonder why the number never finishes the job.",
    desire: "A number that ends anxiety.",
    hiddenFear: "That without money we are nothing.",
    contradictoryBehavior: "Earning more while expanding lifestyle to keep anxiety constant.",
    cost: "Golden handcuffs; relationships scored in currency.",
    category: "SOCIETY",
    node: "money",
    secondaryConflicts: ["FEAR/uncertainty", "EGO/status"],
    universalityScore: 0.91,
    depthScore: 0.84,
    noveltyScore: 0.55,
    recognitionScore: 0.92,
    status: "approved",
    emotions: ["anxiety", "craving"],
    domains: ["money", "status"],
    lenses: ["cultural", "psychological"], exceptional: true,
  },
  {
    statement: "Success without a private definition becomes a public costume contest.",
    observation: "People inherit metrics (title, followers, net worth) and call the inheritance ambition.",
    desire: "A finish line that the tribe respects.",
    hiddenFear: "Winning a game we never chose.",
    contradictoryBehavior: "Saying success is personal while posting the same trophies as everyone else.",
    cost: "Hollow victory; midlife collapse after arrival.",
    category: "SOCIETY",
    node: "success",
    secondaryConflicts: ["MEANING/purpose", "EGO/status"],
    universalityScore: 0.9,
    depthScore: 0.86,
    noveltyScore: 0.58,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["emptiness", "pride"],
    domains: ["career", "culture"],
    lenses: ["cultural", "existential"],
  },
  {
    statement: "Work becomes identity when belonging elsewhere feels unavailable.",
    observation: "Overwork is sometimes less about ambition than about the office being the only place one feels real.",
    desire: "A role that answers who am I.",
    hiddenFear: "Weekends that reveal emptiness.",
    contradictoryBehavior: "Complaining about hustle culture while refusing rest that would force confrontation.",
    cost: "Burnout; brittle identity if the job ends.",
    category: "SOCIETY",
    node: "work",
    secondaryConflicts: ["SELF/identity", "ATTACHMENT/identity"],
    universalityScore: 0.89,
    depthScore: 0.85,
    noveltyScore: 0.6,
    recognitionScore: 0.89,
    status: "approved",
    emotions: ["anxiety", "devotion"],
    domains: ["work", "identity"],
    lenses: ["cultural", "psychological"],
  },
  {
    statement: "Social media turns the self into a product and the audience into a volatile market.",
    observation: "People manage impressions like inventory; rejection becomes a crash; approval becomes a high.",
    desire: "Continuous proof of existence.",
    hiddenFear: "Irrelevance in the feed.",
    contradictoryBehavior: "Digital detox announcements posted for engagement.",
    cost: "Attention fractured; relationships performed; envy industrialized.",
    category: "SOCIETY",
    node: "social-media",
    secondaryConflicts: ["EGO/validation", "FEAR/judgment"],
    universalityScore: 0.93,
    depthScore: 0.83,
    noveltyScore: 0.45,
    recognitionScore: 0.95,
    status: "approved",
    emotions: ["craving", "shame"],
    domains: ["social-media", "identity"],
    lenses: ["cultural", "psychological"], exceptional: true,
  },
  {
    statement: "Consumerism sells identity kits for people who no longer receive identity from community.",
    observation: "When belonging weakens, purchasing becomes a substitute initiation rite.",
    desire: "To belong to something — even a brand.",
    hiddenFear: "Being undefined.",
    contradictoryBehavior: "Anti-consumer aesthetics that still require buying the look.",
    cost: "A self assembled from SKUs; endless incompleteness.",
    category: "SOCIETY",
    node: "consumerism",
    secondaryConflicts: ["DESIRE/consumption", "SELF/identity"],
    universalityScore: 0.88,
    depthScore: 0.84,
    noveltyScore: 0.62,
    recognitionScore: 0.88,
    status: "approved",
    emotions: ["longing", "emptiness"],
    domains: ["culture", "money"],
    lenses: ["cultural", "psychological"],
  },
  {
    statement: "Fame promises being known and often delivers being watched without being understood.",
    observation: "Visibility scales faster than intimacy; the famous can be lonely in a crowd of fans.",
    desire: "Significance through attention.",
    hiddenFear: "Ordinary invisibility.",
    contradictoryBehavior: "Claiming to want privacy while optimizing for reach.",
    cost: "Paranoia, image captivity, and relationships that cannot be unobserved.",
    category: "SOCIETY",
    node: "fame",
    secondaryConflicts: ["EGO/validation", "FEAR/loneliness"],
    universalityScore: 0.8,
    depthScore: 0.82,
    noveltyScore: 0.6,
    recognitionScore: 0.82,
    status: "approved",
    emotions: ["hunger", "loneliness"],
    domains: ["culture", "celebrity"],
    lenses: ["cultural", "existential"],
  },
  {
    statement: "Power reveals character because it removes the constraints that were mistaken for virtue.",
    observation: "People credit themselves for goodness that was actually lack of opportunity to be cruel.",
    desire: "Freedom to act without consequence.",
    hiddenFear: "That our virtue was contingent.",
    contradictoryBehavior: "Demanding power for good while building systems without checks.",
    cost: "Corruption; survivors of our unchecked selves.",
    category: "SOCIETY",
    node: "power",
    secondaryConflicts: ["CHARACTER/integrity", "EGO/superiority"],
    universalityScore: 0.87,
    depthScore: 0.9,
    noveltyScore: 0.58,
    recognitionScore: 0.86,
    status: "approved",
    emotions: ["temptation", "pride"],
    domains: ["leadership", "politics"],
    lenses: ["moral", "psychological"], exceptional: true,
  },
  {
    statement: "Conformity is the rent we pay for belonging — until the rent owns the tenant.",
    observation: "People trade authentic preference for tribal safety and call it maturity or professionalism.",
    desire: "To not be exiled.",
    hiddenFear: "Standing alone with our taste and values.",
    contradictoryBehavior: "Celebrating individuality in theory while punishing deviation in practice.",
    cost: "A culture of copies; quiet despair.",
    category: "SOCIETY",
    node: "conformity",
    secondaryConflicts: ["SELF/authenticity", "FEAR/rejection"],
    universalityScore: 0.9,
    depthScore: 0.84,
    noveltyScore: 0.52,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["fear", "resignation"],
    domains: ["culture", "work"],
    lenses: ["cultural", "psychological"],
  },
  {
    statement: "Status signaling is communication for people who fear being measured by character alone.",
    observation: "Goods, opinions, and aesthetics become billboards; the self hides behind the brand.",
    desire: "To be ranked without being known.",
    hiddenFear: "That character would not rank.",
    contradictoryBehavior: "Mocking flex culture while flexing in subtler dialects.",
    cost: "Attention wasted on signals; envy as the social atmosphere.",
    category: "SOCIETY",
    node: "status-signaling",
    secondaryConflicts: ["EGO/status", "SOCIETY/consumerism"],
    universalityScore: 0.89,
    depthScore: 0.83,
    noveltyScore: 0.6,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["pride", "envy"],
    domains: ["culture", "social-media"],
    lenses: ["cultural", "economic"],
  },
  {
    statement: "People confuse intensity with intimacy and then wonder why calm love feels like indifference.",
    observation: "Chaos-bonded nervous systems misread safety as boredom.",
    desire: "Passion that never rests.",
    hiddenFear: "That peace means the spark is dead.",
    contradictoryBehavior: "Choosing drama then complaining of instability.",
    cost: "Repeating turbulent relationships; discarding healthy partners.",
    category: "RELATIONSHIPS",
    node: "love",
    secondaryConflicts: ["ATTACHMENT/people", "FEAR/abandonment"],
    universalityScore: 0.88,
    depthScore: 0.86,
    noveltyScore: 0.68,
    recognitionScore: 0.89,
    status: "approved",
    emotions: ["confusion", "longing"],
    domains: ["romance", "attachment"],
    lenses: ["psychological"],
  },
  {
    statement: "We outsource moral thinking to tribes and then feel virtuous for the outsourcing.",
    observation: "Positions arrive pre-packaged; dissent inside the tribe is punished more than vice outside it.",
    desire: "Moral certainty with social cover.",
    hiddenFear: "Having to think alone.",
    contradictoryBehavior: "Praising critical thinking while only criticizing outgroups.",
    cost: "Ethical immaturity; cruelty justified as righteousness.",
    category: "SOCIETY",
    node: "conformity",
    secondaryConflicts: ["ATTACHMENT/beliefs", "EGO/need-to-be-right"],
    universalityScore: 0.87,
    depthScore: 0.88,
    noveltyScore: 0.7,
    recognitionScore: 0.86,
    status: "needs_research",
    emotions: ["righteousness", "fear"],
    domains: ["politics", "culture"],
    lenses: ["moral", "epistemic"],
  },
  {
    statement: "Burnout is sometimes the body refusing a life the ego still insists on.",
    observation: "Exhaustion becomes the only permitted no.",
    desire: "Permission to stop without being lazy.",
    hiddenFear: "That stopping reveals we were never enough.",
    contradictoryBehavior: "Resting only when medically forced.",
    cost: "Health as the final bargaining chip.",
    category: "SOCIETY",
    node: "work",
    secondaryConflicts: ["DESIRE/ambition", "SELF/self-worth"],
    universalityScore: 0.9,
    depthScore: 0.85,
    noveltyScore: 0.58,
    recognitionScore: 0.92,
    status: "used",
    emotions: ["exhaustion", "grief"],
    domains: ["work", "health"],
    lenses: ["psychological", "cultural"],
  },
  {
    statement: "Just be positive is often a demand that someone else's pain not inconvenience our comfort.",
    observation: "Forced positivity is emotional control dressed as encouragement.",
    desire: "A mood environment that doesn't challenge us.",
    hiddenFear: "Contagion of despair.",
    contradictoryBehavior: "Posting mental health awareness while shutting down hard conversations.",
    cost: "Isolation of sufferers; shallow culture.",
    category: "SUFFERING",
    node: "grief",
    secondaryConflicts: ["RELATIONSHIPS/boundaries", "SELF/shame"],
    universalityScore: 0.86,
    depthScore: 0.82,
    noveltyScore: 0.65,
    recognitionScore: 0.88,
    status: "approved",
    emotions: ["invalidation", "anger"],
    domains: ["culture", "mental-health"],
    lenses: ["psychological", "cultural"],
  },
  {
    statement: "We keep score in relationships and call it fairness, then wonder why generosity died.",
    observation: "Transactional love turns every gift into a ledger entry.",
    desire: "Perfect reciprocity.",
    hiddenFear: "Being the one who loves more.",
    contradictoryBehavior: "Saying love isn't transactional while tracking favors.",
    cost: "Bookkeeping intimacy; quiet exits.",
    category: "RELATIONSHIPS",
    node: "love",
    secondaryConflicts: ["EGO/resentment", "ATTACHMENT/expectations"],
    universalityScore: 0.87,
    depthScore: 0.83,
    noveltyScore: 0.55,
    recognitionScore: 0.88,
    status: "candidate",
    emotions: ["resentment", "hurt"],
    domains: ["romance", "friendship"],
    lenses: ["psychological"],
  },
  {
    statement: "Hustle maxims that ignore the body are theology for people who worship output.",
    observation: "Generic grind advice treats humans as CPUs with unlimited uptime.",
    desire: "A formula that removes human limits.",
    hiddenFear: "Accepting finitude.",
    contradictoryBehavior: "Sharing sleep-is-for-the-weak content from a burnt-out account.",
    cost: "Normalized self-harm branded as ambition.",
    category: "SOCIETY",
    node: "success",
    secondaryConflicts: ["CHARACTER/discipline", "FEAR/death"],
    universalityScore: 0.84,
    depthScore: 0.78,
    noveltyScore: 0.5,
    recognitionScore: 0.85,
    status: "rejected",
    emotions: ["anger", "exhaustion"],
    domains: ["work", "culture"],
    lenses: ["cultural", "critical"],
  },
  {
    statement: "Childhood roles are unpaid jobs we keep working in adult rooms.",
    observation: "The peacemaker, the achiever, the invisible one — still clocking in.",
    desire: "To be free of the original assignment.",
    hiddenFear: "That without the role we lose our place.",
    contradictoryBehavior: "Therapy language about boundaries while performing the old job at holidays.",
    cost: "Adult life as sequel; partners cast as parents.",
    category: "RELATIONSHIPS",
    node: "family",
    secondaryConflicts: ["SELF/identity", "ATTACHMENT/past"],
    universalityScore: 0.89,
    depthScore: 0.88,
    noveltyScore: 0.62,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["fatigue", "longing"],
    domains: ["family", "identity"],
    lenses: ["psychological"], exceptional: true,
  },
  {
    statement: "We fear being average more than we fear being unhappy.",
    observation: "Mediocrity terror drives extreme choices that destroy ordinary goods.",
    desire: "Specialness as salvation.",
    hiddenFear: "Statistical oblivion.",
    contradictoryBehavior: "Romanticizing simple living while optimizing for exceptionalism.",
    cost: "Discarding good-enough lives for highlight potential.",
    category: "EGO",
    node: "status",
    secondaryConflicts: ["SELF/insecurity", "SOCIETY/success"],
    universalityScore: 0.88,
    depthScore: 0.85,
    noveltyScore: 0.7,
    recognitionScore: 0.87,
    status: "approved",
    emotions: ["anxiety", "ambition"],
    domains: ["culture", "identity"],
    lenses: ["cultural", "existential"],
  },
  {
    statement: "Silence in a relationship is not always peace — sometimes it is two people abandoning the repair.",
    observation: "Conflict avoidance accumulates interest; the blowup is the foreclosure.",
    desire: "Harmony without the labor of truth.",
    hiddenFear: "That truth will end the bond.",
    contradictoryBehavior: "Praising communication while changing the subject at heat.",
    cost: "Sudden endings that were slow deaths.",
    category: "RELATIONSHIPS",
    node: "boundaries",
    secondaryConflicts: ["CHARACTER/honesty", "FEAR/abandonment"],
    universalityScore: 0.9,
    depthScore: 0.84,
    noveltyScore: 0.55,
    recognitionScore: 0.91,
    status: "approved",
    emotions: ["avoidance", "tension"],
    domains: ["romance", "marriage"],
    lenses: ["psychological"],
  },
  {
    statement: "Attention is the new scarcity — and we spend it like drunk heirs.",
    observation: "People protect money and waste focus, then wonder why their inner life feels ransacked.",
    desire: "Presence on demand.",
    hiddenFear: "Missing out while attending.",
    contradictoryBehavior: "Buying focus tools while refusing to close tabs.",
    cost: "Shallow work; shallow love; shallow self.",
    category: "SOCIETY",
    node: "social-media",
    secondaryConflicts: ["DESIRE/novelty", "CHARACTER/self-control"],
    universalityScore: 0.92,
    depthScore: 0.82,
    noveltyScore: 0.55,
    recognitionScore: 0.93,
    status: "approved",
    emotions: ["scattered", "regret"],
    domains: ["attention", "tech"],
    lenses: ["cultural", "behavioral"],
  },
  {
    statement: "We want mentors until they tell us something that threatens our preferred story.",
    observation: "Advice is welcome when it confirms; costly when it corrects.",
    desire: "Guidance without ego death.",
    hiddenFear: "Being a beginner again.",
    contradictoryBehavior: "Asking for honesty then punishing it.",
    cost: "Stagnation with the appearance of seeking.",
    category: "EGO",
    node: "pride",
    secondaryConflicts: ["CHARACTER/honesty", "SELF/self-deception"],
    universalityScore: 0.86,
    depthScore: 0.83,
    noveltyScore: 0.6,
    recognitionScore: 0.87,
    status: "retired",
    emotions: ["pride", "shame"],
    domains: ["growth", "work"],
    lenses: ["psychological", "stoic"],
  },
  {
    statement: "Healing is not a vibe — it is repetitive, boring choices that rewire what chaos once wired.",
    observation: "People want catharsis; nervous systems change through consistency.",
    desire: "A breakthrough that finishes the work.",
    hiddenFear: "That healing is endless.",
    contradictoryBehavior: "Collecting breakthrough moments while skipping the daily practice.",
    cost: "Insight without embodiment; relapse into old patterns.",
    category: "SELF",
    node: "shame",
    secondaryConflicts: ["CHARACTER/discipline", "SUFFERING/grief"],
    universalityScore: 0.89,
    depthScore: 0.87,
    noveltyScore: 0.62,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["hope", "frustration"],
    domains: ["healing", "habits"],
    lenses: ["psychological", "behavioral"],
  },
  {
    statement: "The need to be understood can become a refusal to grow past the story that needs understanding.",
    observation: "Identity as the wounded one can resist the very healing that would retire the role.",
    desire: "Witness for our pain.",
    hiddenFear: "That without the wound we are uninteresting or unowed.",
    contradictoryBehavior: "Seeking therapy while defending the narrative against progress.",
    cost: "Chronic stuckness; relationships drafted as audiences.",
    category: "SELF",
    node: "identity",
    secondaryConflicts: ["SUFFERING/grief", "EGO/validation"],
    universalityScore: 0.87,
    depthScore: 0.89,
    noveltyScore: 0.72,
    recognitionScore: 0.86,
    status: "approved",
    emotions: ["ambivalence", "grief"],
    domains: ["healing", "identity"],
    lenses: ["psychological", "existential"], exceptional: true,
  },
  {
    statement: "Moral licensing lets us do harm after doing good — the good becomes a coupon.",
    observation: "People keep ethical credit scores in their heads and spend them on exemptions.",
    desire: "Virtue without continuous cost.",
    hiddenFear: "That goodness is a depleting resource we must bank.",
    contradictoryBehavior: "Public virtue, private exception.",
    cost: "Hypocrisy; eroded trust.",
    category: "CHARACTER",
    node: "integrity",
    secondaryConflicts: ["SELF/self-deception", "EGO/pride"],
    universalityScore: 0.85,
    depthScore: 0.84,
    noveltyScore: 0.68,
    recognitionScore: 0.84,
    status: "needs_research",
    emotions: ["smugness", "guilt"],
    domains: ["ethics", "behavior"],
    lenses: ["moral", "behavioral"],
  },
  {
    statement: "We treat loneliness with stimulation and call the hangover fate.",
    observation: "Noise, scrolling, and shallow contact mute loneliness without metabolizing it.",
    desire: "Not to feel the void.",
    hiddenFear: "That the void is the truth of the self.",
    contradictoryBehavior: "Scheduling solitude then filling it with content.",
    cost: "Never learning the skill of being with oneself.",
    category: "FEAR",
    node: "loneliness",
    secondaryConflicts: ["DESIRE/novelty", "SOCIETY/social-media"],
    universalityScore: 0.9,
    depthScore: 0.86,
    noveltyScore: 0.6,
    recognitionScore: 0.91,
    status: "approved",
    emotions: ["loneliness", "restlessness"],
    domains: ["mental-health", "tech"],
    lenses: ["existential", "psychological"],
  },
  {
    statement: "Jealousy is the imagination casting the partner in a film where we are already replaced.",
    observation: "The mind rehearses loss until the body reacts as if it already happened.",
    desire: "Exclusive certainty.",
    hiddenFear: "Replaceability.",
    contradictoryBehavior: "Demanding transparency while hiding our own private comparisons.",
    cost: "Surveillance dynamics; eroded trust even when nothing happened.",
    category: "RELATIONSHIPS",
    node: "love",
    secondaryConflicts: ["FEAR/abandonment", "EGO/comparison"],
    universalityScore: 0.88,
    depthScore: 0.84,
    noveltyScore: 0.58,
    recognitionScore: 0.89,
    status: "approved",
    emotions: ["jealousy", "fear"],
    domains: ["romance", "attachment"],
    lenses: ["psychological"],
  },
  {
    statement: "We inherit enemies from our tribes and call the inheritance principle.",
    observation: "Hostility arrives preloaded; questioning it feels like betrayal of the group.",
    desire: "Belonging with a ready-made moral map.",
    hiddenFear: "Having to judge case by case.",
    contradictoryBehavior: "Preaching nuance while sharing caricatures.",
    cost: "Perpetual conflict; inability to see the human across the line.",
    category: "SOCIETY",
    node: "conformity",
    secondaryConflicts: ["ATTACHMENT/beliefs", "EGO/need-to-be-right"],
    universalityScore: 0.86,
    depthScore: 0.85,
    noveltyScore: 0.66,
    recognitionScore: 0.85,
    status: "approved",
    emotions: ["anger", "loyalty"],
    domains: ["politics", "culture"],
    lenses: ["cultural", "moral"],
  },
  {
    statement: "Procrastination is often emotional avoidance wearing a time management costume.",
    observation: "The delayed task is attached to fear, shame, or boredom — not calendar incompetence alone.",
    desire: "To not feel what starting would evoke.",
    hiddenFear: "Judgment of the imperfect attempt.",
    contradictoryBehavior: "Building elaborate systems instead of touching the hard thing for five minutes.",
    cost: "Compounded anxiety; identity as the person who almost starts.",
    category: "CHARACTER",
    node: "discipline",
    secondaryConflicts: ["FEAR/failure", "SELF/shame"],
    universalityScore: 0.91,
    depthScore: 0.83,
    noveltyScore: 0.55,
    recognitionScore: 0.93,
    status: "approved",
    emotions: ["avoidance", "shame"],
    domains: ["habits", "work"],
    lenses: ["psychological", "behavioral"],
  },
  {
    statement: "Apology without changed behavior is theater for the conscience.",
    observation: "Words reset the social moment; patterns reveal the truth.",
    desire: "Absolution that restores access.",
    hiddenFear: "That real change would cost identity or pleasure.",
    contradictoryBehavior: "Mastering apology language while neglecting repair actions.",
    cost: "Trust that cannot return; cynicism in the injured.",
    category: "CHARACTER",
    node: "honesty",
    secondaryConflicts: ["SELF/guilt", "RELATIONSHIPS/forgiveness"],
    universalityScore: 0.9,
    depthScore: 0.86,
    noveltyScore: 0.52,
    recognitionScore: 0.92,
    status: "approved",
    emotions: ["guilt", "distrust"],
    domains: ["relationships", "character"],
    lenses: ["moral", "psychological"],
  },
  {
    statement: "We chase peak experiences and then lose the craft of ordinary joy.",
    observation: "When life is measured in peaks, valleys feel like failure rather than terrain.",
    desire: "Continuous elevation.",
    hiddenFear: "That ordinary is empty.",
    contradictoryBehavior: "Planning epic trips while being numb on weeknights.",
    cost: "Addiction to intensity; contempt for daily life.",
    category: "DESIRE",
    node: "novelty",
    secondaryConflicts: ["MEANING/gratitude", "SUFFERING/meaninglessness"],
    universalityScore: 0.87,
    depthScore: 0.84,
    noveltyScore: 0.6,
    recognitionScore: 0.88,
    status: "approved",
    emotions: ["restlessness", "emptiness"],
    domains: ["lifestyle", "wellbeing"],
    lenses: ["existential", "buddhist"],
  },
  {
    statement: "Control is a counterfeit of safety that raises the cost of every surprise.",
    observation: "Micromanaging people and outcomes reduces anxiety briefly and increases fragility long-term.",
    desire: "A world without variance.",
    hiddenFear: "Helplessness.",
    contradictoryBehavior: "Saying trust the process while gripping every variable.",
    cost: "Exhaustion; others withdrawing; panic when control fails.",
    category: "FEAR",
    node: "uncertainty",
    secondaryConflicts: ["ATTACHMENT/expectations", "CHARACTER/patience"],
    universalityScore: 0.89,
    depthScore: 0.85,
    noveltyScore: 0.55,
    recognitionScore: 0.9,
    status: "approved",
    emotions: ["anxiety", "control"],
    domains: ["work", "relationships"],
    lenses: ["psychological", "stoic"],
  },
];
